# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20171211_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
