# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20171211_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='name',
        ),
    ]
