# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20171211_1001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='WebsitePost',
        ),
    ]
